spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_demo?serverTimezone=UTC&useSSL=false
    username: root
    password: xu12chuan
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
    cache: false
  mvc:
    view:
      prefix: /templates

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.Entity
  configuration:
    map-underscore-to-camel-case: true # springboot - mybatis - 下划线与驼峰自动转换

server:
  port: 9008



#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql
